# Generated by Django 4.1.7 on 2023-03-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='is_day',
            field=models.BooleanField(default=True),
        ),
    ]
